using WebPlatform.Api.Models;

namespace WebPlatform.Api.Dtos;

/**
 * DTO (Data Transfer Object) class, used to transfer data between the
 * client and the server. It is used to define the shape of the data
 * that is sent in the request body when creating or updating a book.
 * The properties of the class exclude Id, as this is automatically
 * generated by the database, and should not be provided by the client.
**/

public class BookRequest
{
    public string? ISBN { get; set; }
    public string Title { get; set; } = "";
    public string Author { get; set; } = "";
    public int? PublicationYear { get; set; }
    public string Publisher { get; set; } = "";
    public string Language { get; set; } = "";
    public string Description { get; set; } = "";
    public decimal Price { get; set; }
    public BookCondition Condition { get; set; }
}
