using System.ComponentModel.DataAnnotations;
using WebPlatform.Api.Models;

namespace WebPlatform.Api.Dtos;

/**
 * DTO (Data Transfer Object) class, used to transfer data between the
 * client and the server. It is used to define the shape of the data
 * that is sent in the request body when creating or updating a book.
 * The properties of the class exclude Id, as this is automatically
 * generated by the database, and should not be provided by the client.
**/

public record BookRequest
{
    public string? ISBN { get; init; }

    [Required]
    public string Title { get; init; } = "";

    [Required]
    public string Author { get; init; } = "";

    // Range chosen for PublicationYear: 1000 is comfortably before the
    // printing press (~1440), so it rejects obvious garbage (negative
    // numbers, stray digits) without any risk of rejecting a real book.
    // 2100 is a soft "not absurdly far in the future" ceiling — it isn't
    // tied to the current year because [Range] requires a compile-time
    // constant and can't call DateTime.Now.
    [Range(1000, 2100)]
    public int? PublicationYear { get; init; }

    public string Publisher { get; init; } = "";
    public string Language { get; init; } = "";
    public string Description { get; init; } = "";

    [Range(0, double.MaxValue)]
    public decimal Price { get; init; }

    public BookCondition Condition { get; init; }
}
